### ISSUE TITLE
Add Documentation on p5.Graphics?

### ISSUE THREAD

**Issue by duskvirkus** [bohnacker/p5js-screenPosition#2]
From what I've found using the `addScreenPositionFunction()` on a p5.Graphics object works fine. But I don't know if this is universal. Anyways here's an example sketch if you think it's worth adding to the documentation.

```
let graphics;

function setup() {
  createCanvas(400, 400);
  graphics = createGraphics(width, height, WEBGL);
  addScreenPositionFunction(graphics);
  
  rectMode(CENTER)
  graphics.rectMode(CENTER);
}

function draw() {
  background(220);
  
  graphics.clear();
  graphics.rotateX(0.010);
  graphics.rotateY(0.011);
  graphics.rotateZ(0.012);
  graphics.square(0, 0, 200);
  image(graphics, 0, 0);
  
  push();
  translate(width/2, height/2);
  const gPoint = graphics.screenPosition(100, 0, 0);
  fill(0, 0, 255);
  square(gPoint.x, gPoint.y, 20);
  pop();
}
```
By the way thanks for making this library it's been super useful!

**Comment by bohnacker** [comment]
Great, thanks for that @figraham ! 👏👍
It's definitely worth adding to the documention and I've already done it.

I think the screenPosition function should generally work with p5.Graphics objects. Maybe there is something that I haven't thougth of. If you find a problem, let me know.
